# Generated by Django 6.0 on 2026-02-13 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_loginattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_locked', 'Login Locked'), ('login_denied', 'Login Denied'), ('register_success', 'Register Success'), ('logout', 'Logout'), ('password_changed', 'Password Changed'), ('user_banned', 'User Banned'), ('user_soft_deleted', 'User Soft Deleted'), ('user_reactivated', 'User Reactivated'), ('user_role_changed', 'User Role Changed')], db_index=True, max_length=40)),
                ('username', models.CharField(blank=True, db_index=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
