# Generated by Django 6.0 on 2026-02-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0006_passwordhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityauditlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login_success", "Login Success"),
                    ("login_failed", "Login Failed"),
                    ("login_locked", "Login Locked"),
                    ("login_denied", "Login Denied"),
                    ("register_success", "Register Success"),
                    ("logout", "Logout"),
                    ("password_changed", "Password Changed"),
                    ("user_banned", "User Banned"),
                    ("user_unbanned", "User Unbanned"),
                    ("user_soft_deleted", "User Soft Deleted"),
                    ("user_reactivated", "User Reactivated"),
                    ("user_role_changed", "User Role Changed"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
