# Generated by Django 6.0 on 2026-02-14 07:48

from django.db import migrations, models


def migrate_trick_status_forward(apps, schema_editor):
    TrickEntry = apps.get_model("wiki", "TrickEntry")
    TrickEntry.objects.filter(status="visible").update(status="approved")
    TrickEntry.objects.filter(status="hidden").update(status="rejected")


def migrate_trick_status_backward(apps, schema_editor):
    TrickEntry = apps.get_model("wiki", "TrickEntry")
    TrickEntry.objects.filter(status="approved").update(status="visible")
    TrickEntry.objects.filter(status="rejected").update(status="hidden")


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_trickentry'),
    ]

    operations = [
        migrations.RunPython(
            migrate_trick_status_forward,
            migrate_trick_status_backward,
        ),
        migrations.AlterField(
            model_name='trickentry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
    ]
