# Generated by Django 6.0 on 2026-02-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0009_alter_trickentry_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlecomment",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("visible", "Visible"), ("hidden", "Hidden")],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
