# Generated by Django 6.0 on 2026-02-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0010_alter_articlecomment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issueticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
