# Generated by Django 6.0 on 2026-02-28 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendlyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=500)),
                ('is_enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friendly_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
