# Generated by Django 6.0 on 2026-02-28 15:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0013_friendlylink"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitionNotice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=220)),
                ("content_md", models.TextField()),
                (
                    "series",
                    models.CharField(
                        choices=[
                            ("icpc", "ICPC"),
                            ("ccpc", "CCPC"),
                            ("lanqiao", "蓝桥杯"),
                            ("tianti", "天梯赛"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("year", models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("general", "通用"),
                            ("regional_invitation", "区域赛/邀请赛"),
                            ("provincial_network", "省赛/网络赛"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=40,
                    ),
                ),
                ("is_visible", models.BooleanField(db_index=True, default=True)),
                ("published_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competition_notices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edited_competition_notices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CompetitionScheduleEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_date", models.DateField(db_index=True)),
                ("competition_type", models.CharField(max_length=120)),
                ("location", models.CharField(max_length=200)),
                ("qq_group", models.CharField(blank=True, max_length=160)),
                (
                    "announcement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_entries",
                        to="wiki.competitionnotice",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_competition_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_competition_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["event_date", "id"],
            },
        ),
    ]
