# Generated by Django 6.0 on 2026-03-01

from django.db import migrations, models


def split_legacy_stage_values(apps, schema_editor):
    CompetitionNotice = apps.get_model("wiki", "CompetitionNotice")
    CompetitionNotice.objects.filter(stage="regional_invitation").update(stage="regional")
    CompetitionNotice.objects.filter(stage="provincial_network").update(stage="provincial")


def merge_stage_values_for_rollback(apps, schema_editor):
    CompetitionNotice = apps.get_model("wiki", "CompetitionNotice")
    CompetitionNotice.objects.filter(stage__in=["regional", "invitational"]).update(stage="regional_invitation")
    CompetitionNotice.objects.filter(stage__in=["provincial", "network"]).update(stage="provincial_network")


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0014_competition_notice_competitionscheduleentry"),
    ]

    operations = [
        migrations.RunPython(split_legacy_stage_values, merge_stage_values_for_rollback),
        migrations.AlterField(
            model_name="competitionnotice",
            name="stage",
            field=models.CharField(
                choices=[
                    ("general", "通用"),
                    ("regional", "区域赛"),
                    ("invitational", "邀请赛"),
                    ("provincial", "省赛"),
                    ("network", "网络赛"),
                ],
                db_index=True,
                default="general",
                max_length=40,
            ),
        ),
    ]
