# Generated by Django 6.0 on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0015_competition_notice_stage_split"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionscheduleentry",
            name="competition_time_range",
            field=models.CharField(blank=True, default="", max_length=60),
            preserve_default=False,
        ),
    ]
