# Generated by Django 6.0 on 2026-03-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0016_competition_schedule_time_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionnotice',
            name='series',
            field=models.CharField(choices=[('icpc', 'ICPC'), ('ccpc', 'CCPC'), ('lanqiao', 'Lanqiao'), ('tianti', 'Tianti')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='competitionnotice',
            name='stage',
            field=models.CharField(choices=[('general', 'General'), ('regional', 'Regional'), ('invitational', 'Invitational'), ('provincial', 'Provincial'), ('network', 'Network')], db_index=True, default='general', max_length=40),
        ),
    ]
