# Generated by Django 6.0 on 2026-03-28 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0020_competitioncalendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='securityauditlog',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_locked', 'Login Locked'), ('login_denied', 'Login Denied'), ('register_success', 'Register Success'), ('register_code_sent', 'Register Code Sent'), ('logout', 'Logout'), ('password_changed', 'Password Changed'), ('password_reset_requested', 'Password Reset Requested'), ('password_reset_completed', 'Password Reset Completed'), ('email_change_requested', 'Email Change Requested'), ('email_changed', 'Email Changed'), ('user_banned', 'User Banned'), ('user_unbanned', 'User Unbanned'), ('user_soft_deleted', 'User Soft Deleted'), ('user_reactivated', 'User Reactivated'), ('user_role_changed', 'User Role Changed')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='EmailVerificationTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('register', 'Register'), ('reset_password', 'Reset Password'), ('change_email', 'Change Email')], db_index=True, max_length=32)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('username_snapshot', models.CharField(blank=True, max_length=150)),
                ('school_name_snapshot', models.CharField(blank=True, max_length=120)),
                ('password_hash_snapshot', models.CharField(blank=True, max_length=128)),
                ('code_hash', models.CharField(max_length=128)),
                ('verify_attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('created_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
