# Generated by Django 6.0 on 2026-03-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0021_user_email_verified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationticket',
            name='purpose',
            field=models.CharField(choices=[('register', 'Register'), ('reset_password', 'Reset Password'), ('change_email', 'Change Email'), ('change_password', 'Change Password')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='securityauditlog',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_locked', 'Login Locked'), ('login_denied', 'Login Denied'), ('register_success', 'Register Success'), ('register_code_sent', 'Register Code Sent'), ('logout', 'Logout'), ('password_change_requested', 'Password Change Requested'), ('password_changed', 'Password Changed'), ('password_reset_requested', 'Password Reset Requested'), ('password_reset_completed', 'Password Reset Completed'), ('email_change_requested', 'Email Change Requested'), ('email_changed', 'Email Changed'), ('user_banned', 'User Banned'), ('user_unbanned', 'User Unbanned'), ('user_soft_deleted', 'User Soft Deleted'), ('user_hard_deleted', 'User Hard Deleted'), ('user_reactivated', 'User Reactivated'), ('user_role_changed', 'User Role Changed')], db_index=True, max_length=40),
        ),
    ]
