# Generated by Django 6.0 on 2026-04-01 15:10

import django.db.models.deletion
from django.db import migrations, models


def populate_article_display_order_and_zone_sections(apps, schema_editor):
    Article = apps.get_model("wiki", "Article")
    CompetitionZoneSection = apps.get_model("wiki", "CompetitionZoneSection")

    category_ids = (
        Article.objects.order_by("category_id")
        .values_list("category_id", flat=True)
        .distinct()
    )
    for category_id in category_ids:
        articles = list(
            Article.objects.filter(category_id=category_id).order_by("created_at", "id")
        )
        for index, article in enumerate(articles, start=1):
            if article.display_order != index:
                article.display_order = index
                article.save(update_fields=["display_order"])

    default_sections = [
        ("比赛日历表", "calendar", "calendar", 1),
        ("trick技巧", "tricks", "tricks", 2),
        ("赛事时刻表", "schedule", "schedule", 3),
        ("赛事公告", "notice", "notice", 4),
        ("问答", "qa", "qa", 5),
    ]
    for title, key, builtin_view, display_order in default_sections:
        CompetitionZoneSection.objects.update_or_create(
            key=key,
            defaults={
                "title": title,
                "target_type": "builtin",
                "builtin_view": builtin_view,
                "display_order": display_order,
                "is_visible": True,
            },
        )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0022_alter_emailverificationticket_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.CreateModel(
            name='CompetitionZoneSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('target_type', models.CharField(choices=[('builtin', 'Built-in'), ('page', 'Page')], default='builtin', max_length=20)),
                ('builtin_view', models.CharField(blank=True, choices=[('schedule', 'Competition Schedule'), ('notice', 'Competition Notice'), ('practice', 'Practice Links'), ('calendar', 'Competition Calendar'), ('tricks', 'Trick Entries'), ('qa', 'Q&A')], default='', max_length=30)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_zone_sections', to='wiki.extensionpage')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.RunPython(populate_article_display_order_and_zone_sections, noop_reverse),
    ]
