# Generated by Django 6.0 on 2026-04-01 16:56

from django.db import migrations, models


def seed_header_navigation_items(apps, schema_editor):
    HeaderNavigationItem = apps.get_model("wiki", "HeaderNavigationItem")
    defaults = [
        ("home", "首页", 10),
        ("competition-wiki", "竞赛wiki", 20),
        ("competitions", "赛事专区", 30),
        ("about", "关于AlgoWiki", 40),
        ("friendly-links", "友链", 50),
    ]
    for key, title, display_order in defaults:
        HeaderNavigationItem.objects.update_or_create(
            key=key,
            defaults={
                "title": title,
                "display_order": display_order,
                "is_visible": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0023_article_display_order_competitionzonesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderNavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('home', 'Home'), ('competition-wiki', 'Competition Wiki'), ('competitions', 'Competition Zone'), ('about', 'About AlgoWiki'), ('friendly-links', 'Friendly Links')], db_index=True, max_length=40, unique=True)),
                ('title', models.CharField(max_length=80)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.RunPython(seed_header_navigation_items, migrations.RunPython.noop),
    ]
