# Generated by Django 6.0 on 2026-04-09 21:00

from datetime import timedelta

from django.db import migrations, models
from django.utils import timezone


def seed_question_auto_close_at(apps, schema_editor):
    Question = apps.get_model("wiki", "Question")
    now = timezone.now()
    cutoff = now - timedelta(days=7)

    Question.objects.filter(
        status="open",
        created_at__lte=cutoff,
    ).update(
        status="closed",
        auto_close_at=None,
    )

    for question in Question.objects.filter(
        status="open",
        auto_close_at__isnull=True,
        created_at__gt=cutoff,
    ).only("id", "created_at").iterator():
        Question.objects.filter(pk=question.pk).update(
            auto_close_at=question.created_at + timedelta(days=7),
        )


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0023_article_display_order_competitionzonesection"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="auto_close_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(seed_question_auto_close_at, migrations.RunPython.noop),
    ]
