# Generated by Django 6.0 on 2026-04-17 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0039_sync_document_pages_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionnotice',
            name='revision_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_revisions', to='wiki.competitionnotice'),
        ),
    ]
