# Generated by Django 6.0 on 2026-04-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0040_competitionnotice_revision_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionnotice',
            name='stage',
            field=models.CharField(choices=[('general', 'General'), ('regional', 'Regional'), ('invitational', 'Invitational'), ('provincial', 'Provincial'), ('network', 'Network'), ('national', 'National'), ('popular', 'Popular'), ('standard', 'Standard')], db_index=True, default='general', max_length=40),
        ),
    ]
