# Generated by Django 6.0 on 2026-04-22 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_schedule_end_date(apps, _schema_editor):
    CompetitionScheduleEntry = apps.get_model("wiki", "CompetitionScheduleEntry")
    CompetitionScheduleEntry.objects.filter(end_date__isnull=True).update(
        end_date=models.F("event_date")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0041_alter_competitionnotice_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionscheduleentry',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_schedule_end_date, migrations.RunPython.noop),
        migrations.CreateModel(
            name='DeletedContentArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(db_index=True, max_length=80)),
                ('target_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('delete_action', models.CharField(choices=[('delete', 'Delete'), ('hide', 'Hide')], db_index=True, default='delete', max_length=20)),
                ('title', models.CharField(blank=True, max_length=220)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('content_md', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('original_author_name', models.CharField(blank=True, max_length=150)),
                ('deleted_by_name', models.CharField(blank=True, max_length=150)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_content_deleted_archives', to=settings.AUTH_USER_MODEL)),
                ('original_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_content_original_archives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['target_type', 'created_at'], name='wiki_delete_target__063960_idx'), models.Index(fields=['deleted_by', 'created_at'], name='wiki_delete_deleted_491c71_idx'), models.Index(fields=['original_author', 'created_at'], name='wiki_delete_origina_ca82e2_idx')],
            },
        ),
    ]
