# Generated by Django 6.0 on 2026-04-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0042_competitionscheduleentry_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('page_views', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
