# Generated by Django 6.0 on 2026-04-23 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


TRICK_REGULATION_CONTENT = """# Trick 页面贡献值与投票规则

为鼓励优质内容创作，维护 Trick 页面的内容质量，AlgoWiki 在 Trick 页面引入贡献值与投票机制。

贡献值用于衡量用户在 Trick 社区中的有效贡献，并决定部分功能权限。本规则目前仅适用于 Trick 页面。

## 一、贡献值说明

贡献值主要来源包括：

- 提交 Trick 并审核通过
- 自己发布的 Trick 获得点赞
- 参与社区内容纠错并被管理员审核采纳

系统支持查看贡献值明细，包括变动时间、行为类型、对应 Trick、分值变化、变动后贡献值，以及是否为审核修正或回滚产生。

## 二、贡献值变动规则

### 1. 提交 Trick

- 用户提交的 Trick 通过审核后：贡献值 +10
- 若该 Trick 后续被管理员确认删除：贡献值 -10

这里的 -10 用于回滚该条 Trick 曾经带来的投稿收益。

### 2. Trick 被点赞

- 自己发布的 Trick 每获得 1 个点赞：贡献值 +1

用户不得为自己的 Trick 点赞；若点赞被取消，则对应贡献值同步回滚。平台有权对异常刷赞行为进行风控、回滚或处理。

### 3. 点踩行为

满足点踩权限的用户可对 Trick 点踩。

- 点踩时，点踩者：贡献值 -1
- 被点踩的 Trick 作者：贡献值 -2

点踩应用于明显错误、误导、过时、重复、质量过低或与页面定位不符的内容。点踩不等同于删除，删除仍需进入管理员审核流程。

若存在恶意点踩、针对性打击、组织性操作等情况，管理员有权撤销对应记录并追加处理。

### 4. 删除审核通过后的处理

当某条 Trick 因点踩达到阈值并进入管理员审核，最终被确认删除时：

- 该 Trick 作者不再额外扣除贡献值
- 该 Trick 对应的投稿通过收益按规则回滚：-10
- 参与该条 Trick 点踩且判定有效的用户，每人：贡献值 +2

该奖励仅在管理员最终确认删除时发放。若审核后决定保留，则点踩者此前消耗的 -1 不返还。管理员有权对异常点踩收益进行取消、修正或回滚。

## 三、投票权限规则

### 1. 点赞权限

当用户贡献值大于等于 10 时，可使用点赞功能。

### 2. 点踩权限

当用户贡献值大于等于 50 时，可使用点踩功能。

点踩权限门槛高于点赞权限，以降低滥用风险。平台后续可根据社区发展情况调整权限阈值。

## 四、删除审核规则

当某条 Trick 累计达到 5 个点踩时，系统将自动把该 Trick 提交至管理员删除审核队列。

5 个点踩不会直接删除 Trick。管理员将结合内容质量、正确性、时效性、重复情况及页面定位进行人工审核。审核结果可能包括保留、删除或其他必要处理措施。

## 五、通知规则

为保证流程透明，系统会在以下情况下发送站内通知。

### 1. 发送给作者的通知

- Trick 审核通过
- Trick 获得点赞
- Trick 达到点踩阈值并进入删除审核
- Trick 删除审核结束，并告知最终结果

### 2. 发送给点踩用户的通知

- 对应 Trick 已进入删除审核
- 删除审核已结束，并告知最终结果
- 若审核删除成立，告知对应贡献值奖励已发放

## 六、隐私与可见性规则

为避免社区纠纷和报复性行为，点踩记录默认采用匿名保护机制：

- 普通用户不可查看是谁对某条 Trick 进行了点踩
- 作者不可查看具体点踩用户名单
- 管理员可在后台查看必要记录，用于审核、申诉处理与异常行为排查

点赞记录的公开方式可根据页面展示需求另行设计。

## 七、异常行为处理

以下行为属于异常或违规行为，包括但不限于：刷赞、刷踩、小号互刷、组织性互投、恶意打击特定作者、利用机制恶意获取贡献值、通过非正常方式影响 Trick 排名或审核结果。

对于上述行为，管理员有权采取撤销投票、回滚贡献值、限制投票权限、限制发布权限、警告、封禁或其他必要处理措施。

## 八、规则解释与调整

AlgoWiki 有权根据社区发展情况，对本规则进行调整、补充或修订。如规则发生更新，将以页面公告或站内说明为准。
"""


def _add_trick_contribution_event(
    *,
    User,
    TrickContributionEvent,
    user_id,
    delta,
    action_type,
    trick_entry_id,
    trick_title,
    event_key,
    actor_id=None,
    is_rollback=False,
):
    if not user_id or not delta or TrickContributionEvent.objects.filter(event_key=event_key).exists():
        return
    user = User.objects.get(pk=user_id)
    next_score = int(getattr(user, "trick_contribution_score", 0) or 0) + int(delta)
    user.trick_contribution_score = next_score
    user.save(update_fields=["trick_contribution_score"])
    TrickContributionEvent.objects.create(
        user_id=user_id,
        actor_id=actor_id,
        trick_entry_id=trick_entry_id,
        trick_title=str(trick_title or "")[:220],
        action_type=action_type,
        delta=delta,
        balance_after=next_score,
        is_rollback=is_rollback,
        event_key=event_key,
        metadata={"seeded": True, "trick_id": trick_entry_id},
    )


def seed_initial_trick_contributions(apps, schema_editor):
    User = apps.get_model("wiki", "User")
    TrickEntry = apps.get_model("wiki", "TrickEntry")
    TrickEntryLike = apps.get_model("wiki", "TrickEntryLike")
    TrickContributionEvent = apps.get_model("wiki", "TrickContributionEvent")

    for entry in TrickEntry.objects.filter(status="approved").order_by("created_at", "id"):
        _add_trick_contribution_event(
            User=User,
            TrickContributionEvent=TrickContributionEvent,
            user_id=entry.author_id,
            delta=10,
            action_type="trick_approved",
            trick_entry_id=entry.id,
            trick_title=entry.title,
            event_key=f"trick-approved:{entry.id}",
        )

    for like in (
        TrickEntryLike.objects.select_related("trick_entry")
        .filter(trick_entry__status="approved")
        .order_by("created_at", "id")
    ):
        if like.user_id == like.trick_entry.author_id:
            continue
        _add_trick_contribution_event(
            User=User,
            TrickContributionEvent=TrickContributionEvent,
            user_id=like.trick_entry.author_id,
            actor_id=like.user_id,
            delta=1,
            action_type="trick_received_like",
            trick_entry_id=like.trick_entry_id,
            trick_title=like.trick_entry.title,
            event_key=f"trick-like:{like.id}:author",
        )


def create_trick_regulation_doc(apps, schema_editor):
    ExtensionPage = apps.get_model("wiki", "ExtensionPage")
    DocumentPageSection = apps.get_model("wiki", "DocumentPageSection")

    page, _ = ExtensionPage.objects.get_or_create(
        slug="trick-regulation",
        defaults={
            "title": "Trick 页面贡献值与投票规则",
            "description": "用于说明 Trick 页面的贡献值、投票权限与审核规则。",
            "content_md": TRICK_REGULATION_CONTENT,
            "access_level": "public",
            "is_enabled": True,
        },
    )
    if not str(page.content_md or "").strip():
        page.content_md = TRICK_REGULATION_CONTENT
    page.title = "Trick 页面贡献值与投票规则"
    page.description = "用于说明 Trick 页面的贡献值、投票权限与审核规则。"
    page.access_level = "public"
    page.is_enabled = True
    page.save()

    section, _ = DocumentPageSection.objects.get_or_create(
        key="trick-regulation",
        defaults={
            "title": "Trick 页面贡献值与投票规则",
            "page": page,
            "display_order": 25,
            "is_visible": True,
        },
    )
    section.title = "Trick 页面贡献值与投票规则"
    section.page = page
    section.display_order = 25
    section.is_visible = True
    section.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0044_assistantproviderconfig_teaser_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='trickentry',
            name='delete_vote_review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trickentry',
            name='delete_vote_review_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trickentry',
            name='delete_vote_review_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('kept', 'Kept'), ('deleted', 'Deleted')], db_index=True, default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='trickentry',
            name='delete_vote_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trickentry',
            name='delete_vote_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_trick_delete_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='trick_contribution_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.CreateModel(
            name='TrickContributionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trick_title', models.CharField(blank=True, max_length=220)),
                ('action_type', models.CharField(choices=[('trick_approved', 'Trick Approved'), ('trick_approval_rollback', 'Trick Approval Rollback'), ('trick_received_like', 'Trick Received Like'), ('trick_received_like_rollback', 'Trick Received Like Rollback'), ('trick_cast_downvote', 'Trick Cast Downvote'), ('trick_received_downvote', 'Trick Received Downvote'), ('trick_delete_review_reward', 'Trick Delete Review Reward'), ('admin_adjustment', 'Admin Adjustment')], db_index=True, max_length=40)),
                ('delta', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('is_rollback', models.BooleanField(db_index=True, default=False)),
                ('event_key', models.CharField(blank=True, max_length=180, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_trick_contribution_events', to=settings.AUTH_USER_MODEL)),
                ('trick_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_events', to='wiki.trickentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trick_contribution_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='wiki_trickc_user_id_334ed9_idx'), models.Index(fields=['action_type', 'created_at'], name='wiki_trickc_action__dc8367_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrickEntryDownvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trick_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downvote_records', to='wiki.trickentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trick_entry_downvotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'trick_entry')},
            },
        ),
        migrations.RunPython(seed_initial_trick_contributions, migrations.RunPython.noop),
        migrations.RunPython(create_trick_regulation_doc, migrations.RunPython.noop),
    ]
