# Generated by Django 6.0 on 2026-04-29 12:08

import django.db.models.deletion
import wiki.models
from django.conf import settings
from django.db import migrations, models


def seed_default_gallery_folders(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0046_ensure_competition_practice_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImageFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.RunPython(seed_default_gallery_folders, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='trickcontributionevent',
            name='action_type',
            field=models.CharField(choices=[('trick_approved', 'Trick 通过审核'), ('trick_approval_rollback', 'Trick 投稿收益回滚'), ('trick_received_like', 'Trick 收到点赞'), ('trick_received_like_rollback', 'Trick 点赞收益回滚'), ('trick_cast_downvote', '发起 Trick 点踩'), ('trick_received_downvote', 'Trick 收到点踩'), ('trick_delete_review_reward', 'Trick 删除审核奖励'), ('admin_adjustment', '管理员调整')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(max_length=500, upload_to=wiki.models.gallery_image_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('recycled', 'Recycled')], db_index=True, default='active', max_length=20)),
                ('original_path', models.CharField(blank=True, max_length=500)),
                ('recycled_path', models.CharField(blank=True, max_length=500)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('delete_after', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_gallery_images', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='wiki.galleryimagefolder')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='wiki_galler_status_b40508_idx'), models.Index(fields=['folder', 'status'], name='wiki_galler_folder__adf10d_idx')],
            },
        ),
    ]
