# Generated by Django 6.0 on 2026-04-29

from django.db import migrations


def cleanup_empty_seed_folders(apps, schema_editor):
    GalleryImageFolder = apps.get_model("wiki", "GalleryImageFolder")
    GalleryImage = apps.get_model("wiki", "GalleryImage")
    seed_slugs = ["algorithm-diagrams", "article-covers", "site-assets", "general"]
    for folder in GalleryImageFolder.objects.filter(slug__in=seed_slugs):
        if not GalleryImage.objects.filter(folder_id=folder.id).exists():
            folder.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0047_gallery_images"),
    ]

    operations = [
        migrations.RunPython(cleanup_empty_seed_folders, migrations.RunPython.noop),
    ]
