# Generated by Django 6.0 on 2026-05-12 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0048_cleanup_empty_gallery_seed_folders"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModerationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, unique=True
                    ),
                ),
                ("label", models.CharField(default="默认 AI 审核配置", max_length=80)),
                (
                    "provider",
                    models.CharField(
                        choices=[("deepseek", "DeepSeek")],
                        db_index=True,
                        default="deepseek",
                        max_length=20,
                    ),
                ),
                (
                    "base_url",
                    models.URLField(default="https://api.deepseek.com", max_length=500),
                ),
                (
                    "model_name",
                    models.CharField(default="deepseek-chat", max_length=120),
                ),
                ("api_key_encrypted", models.TextField(blank=True)),
                ("is_enabled", models.BooleanField(db_index=True, default=False)),
                ("comment_enabled", models.BooleanField(default=True)),
                ("question_enabled", models.BooleanField(default=True)),
                ("answer_enabled", models.BooleanField(default=True)),
                ("ticket_enabled", models.BooleanField(default=True)),
                ("auto_approve_safe", models.BooleanField(default=True)),
                ("auto_reject_unsafe", models.BooleanField(default=True)),
                (
                    "suspicious_action",
                    models.CharField(
                        choices=[("pending", "Keep Pending"), ("reject", "Reject")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "failure_action",
                    models.CharField(
                        choices=[("pending", "Keep Pending"), ("approve", "Approve")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("temperature", models.FloatField(default=0.0)),
                ("max_output_tokens", models.PositiveIntegerField(default=512)),
                (
                    "request_timeout_seconds",
                    models.PositiveSmallIntegerField(default=20),
                ),
                ("daily_request_limit", models.PositiveIntegerField(default=0)),
                ("daily_token_limit", models.PositiveIntegerField(default=0)),
                ("max_input_chars", models.PositiveIntegerField(default=4000)),
                ("new_user_strict_days", models.PositiveSmallIntegerField(default=7)),
                (
                    "new_user_strict_max_items",
                    models.PositiveSmallIntegerField(default=3),
                ),
                ("whitelist_keywords", models.JSONField(blank=True, default=list)),
                ("blacklist_keywords", models.JSONField(blank=True, default=list)),
                ("blocked_domains", models.JSONField(blank=True, default=list)),
                ("supplemental_rules", models.TextField(blank=True)),
                (
                    "reject_notice_template",
                    models.CharField(
                        default="内容未通过 AI 审核：{reason}。请修改后重新提交。",
                        max_length=300,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ai_moderation_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_ai_moderation_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AIModerationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("comment", "Comment"),
                            ("question", "Question"),
                            ("answer", "Answer"),
                            ("ticket", "Ticket"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("target_id", models.PositiveBigIntegerField(db_index=True)),
                (
                    "provider",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                ("model_name", models.CharField(blank=True, max_length=120)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("manual", "Manual Review"),
                            ("error", "Error"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("safe", "Safe"),
                            ("suspicious", "Suspicious"),
                            ("reject", "Reject"),
                            ("error", "Error"),
                        ],
                        default="suspicious",
                        max_length=20,
                    ),
                ),
                ("categories", models.JSONField(blank=True, default=list)),
                ("summary", models.CharField(blank=True, max_length=300)),
                ("user_notice", models.CharField(blank=True, max_length=300)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("prompt_chars", models.PositiveIntegerField(default=0)),
                ("response_chars", models.PositiveIntegerField(default=0)),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                ("response_ms", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("pending_review", "Pending Review"),
                            ("error", "Error"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending_review",
                        max_length=20,
                    ),
                ),
                ("error_message", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_moderation_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_records",
                        to="wiki.aimoderationconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="wiki_aimode_target__cc152d_idx",
                    ),
                    models.Index(
                        fields=["decision", "created_at"],
                        name="wiki_aimode_decisio_118be2_idx",
                    ),
                ],
            },
        ),
    ]
