# Generated by Django 6.0 on 2026-05-30 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0054_real_name_aliyun_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="unverified",
                        max_length=20,
                    ),
                ),
                (
                    "phone_country_code",
                    models.CharField(blank=True, default="86", max_length=8),
                ),
                ("phone_masked", models.CharField(blank=True, max_length=32)),
                ("phone_last4", models.CharField(blank=True, max_length=4)),
                (
                    "phone_digest",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "provider",
                    models.CharField(blank=True, default="manual", max_length=40),
                ),
                (
                    "provider_out_id",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("provider_biz_id", models.CharField(blank=True, max_length=120)),
                ("provider_request_id", models.CharField(blank=True, max_length=120)),
                (
                    "provider_status_message",
                    models.CharField(blank=True, max_length=300),
                ),
                ("provider_result", models.JSONField(blank=True, default=dict)),
                ("provider_started_at", models.DateTimeField(blank=True, null=True)),
                ("provider_checked_at", models.DateTimeField(blank=True, null=True)),
                ("provider_expires_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.CharField(blank=True, max_length=300)),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_phone_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_verification",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PhoneVerificationTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone_country_code",
                    models.CharField(blank=True, default="86", max_length=8),
                ),
                ("phone_masked", models.CharField(blank=True, max_length=32)),
                ("phone_last4", models.CharField(blank=True, max_length=4)),
                ("phone_digest", models.CharField(db_index=True, max_length=128)),
                (
                    "provider",
                    models.CharField(blank=True, default="aliyun_pnvs", max_length=40),
                ),
                (
                    "provider_out_id",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("provider_biz_id", models.CharField(blank=True, max_length=120)),
                ("provider_request_id", models.CharField(blank=True, max_length=120)),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("verify_attempt_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_ip",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "consumed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_verification_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="wiki_phonev_user_id_67b9b4_idx",
                    ),
                    models.Index(
                        fields=["phone_digest", "created_at"],
                        name="wiki_phonev_phone_d_259fc2_idx",
                    ),
                ],
            },
        ),
    ]
