# Generated by Django 6.0 on 2026-06-01 17:29

import django.db.models.deletion
import wiki.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0055_phone_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="momentimage",
            name="delete_after",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="momentimage",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="momentimage",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_moment_images",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="momentimage",
            name="height",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="momentimage",
            name="last_moderated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="momentimage",
            name="moderation_categories",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="momentimage",
            name="moderation_decision",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name="momentimage",
            name="moderation_error",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="momentimage",
            name="moderation_provider",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="momentimage",
            name="moderation_raw",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="momentimage",
            name="moderation_risk_level",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="momentimage",
            name="recheck_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="momentimage",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                default="",
                upload_to=wiki.models.moment_image_thumbnail_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="momentimage",
            name="thumbnail_height",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="momentimage",
            name="thumbnail_size_bytes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="momentimage",
            name="thumbnail_width",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="momentimage",
            name="width",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="momentimage",
            index=models.Index(
                fields=["status", "created_at"], name="wiki_moment_status_1c7f31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="momentimage",
            index=models.Index(
                fields=["uploaded_by", "created_at"],
                name="wiki_moment_uploade_b7b301_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="momentimage",
            index=models.Index(
                fields=["delete_after"], name="wiki_moment_delete__78eac1_idx"
            ),
        ),
    ]
