# Generated by Codex on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0056_moment_image_hardening"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("private", "Private"),
                ],
                db_index=True,
                default="private",
                max_length=20,
            ),
        ),
    ]
