# Generated by Django 6.0 on 2026-06-14 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0060_school_survey_xcpc_49_online"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaptchaAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scene", models.CharField(db_index=True, max_length=64)),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                ("user_agent", models.TextField(blank=True)),
                (
                    "target_type",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                (
                    "target_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("turnstile_success", models.BooleanField(default=False)),
                ("secondary_provider", models.CharField(blank=True, max_length=32)),
                ("secondary_success", models.BooleanField(default=False)),
                ("result", models.CharField(db_index=True, max_length=32)),
                (
                    "error_code",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="captcha_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["scene", "created_at"], name="captcha_scene_created_idx"
                    ),
                    models.Index(
                        fields=["target_type", "target_hash"],
                        name="captcha_target_hash_idx",
                    ),
                ],
            },
        ),
    ]
