# Generated by Codex on 2026-06-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0061_captchaauditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="phoneverification",
            name="phone_encrypted",
            field=models.TextField(blank=True),
        ),
    ]
