# Generated by Django 6.0 on 2026-06-18 10:36

from django.db import migrations, models


def mark_existing_published_announcements_notified(apps, schema_editor):
    Announcement = apps.get_model("wiki", "Announcement")
    Announcement.objects.filter(is_published=True, notified_at__isnull=True).update(
        notified_at=models.F("created_at")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0062_phoneverification_phone_encrypted"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="archived_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="level",
            field=models.CharField(
                choices=[
                    ("emergency", "Emergency"),
                    ("important", "Important"),
                    ("normal", "Normal"),
                    ("low", "Low"),
                ],
                db_index=True,
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="requires_ack",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="announcement",
            name="send_notification",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="show_as_banner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="announcement",
            name="show_as_popup",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="show_in_list",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="show_on_home",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="summary",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="announcement",
            name="target_audience",
            field=models.CharField(
                choices=[
                    ("all", "All visitors"),
                    ("logged_in", "Logged-in users"),
                    ("school", "School users"),
                    ("admin", "Admins"),
                ],
                db_index=True,
                default="all",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="withdrawn_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            mark_existing_published_announcements_notified,
            migrations.RunPython.noop,
        ),
    ]
