# Generated by Django 6.0 on 2026-06-18 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0063_announcement_archived_at_announcement_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverificationticket",
            name="invitation_code_snapshot",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="user",
            name="invitation_score",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.CreateModel(
            name="InvitationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=32, unique=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("used_count", models.PositiveIntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitation_code",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvitationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code_snapshot", models.CharField(db_index=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("effective", "Effective"),
                            ("rolled_back", "Rolled Back"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reward_delta", models.IntegerField(default=1)),
                (
                    "registration_ip_hash",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                (
                    "user_agent_hash",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("effective_at", models.DateTimeField(blank=True, null=True)),
                ("rolled_back_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.CharField(blank=True, max_length=300)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "invitation_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="wiki.invitationcode",
                    ),
                ),
                (
                    "invitee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitation_record",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_invitation_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="InvitationContributionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("invitation_effective", "Invitation Effective"),
                            ("invitation_rollback", "Invitation Rollback"),
                            ("admin_adjustment", "Admin Adjustment"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("delta", models.IntegerField()),
                ("balance_after", models.IntegerField()),
                ("is_rollback", models.BooleanField(db_index=True, default=False)),
                (
                    "event_key",
                    models.CharField(
                        blank=True, max_length=180, null=True, unique=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_invitation_contribution_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitation_contribution_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invitation_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contribution_events",
                        to="wiki.invitationrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="invitationrecord",
            index=models.Index(
                fields=["inviter", "status", "created_at"],
                name="wiki_invita_inviter_3d0102_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invitationrecord",
            index=models.Index(
                fields=["status", "created_at"], name="wiki_invita_status_595d5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invitationrecord",
            index=models.Index(
                fields=["code_snapshot", "created_at"],
                name="wiki_invita_code_sn_ce4f47_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invitationcontributionevent",
            index=models.Index(
                fields=["user", "created_at"], name="wiki_invita_user_id_24fcb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invitationcontributionevent",
            index=models.Index(
                fields=["action_type", "created_at"],
                name="wiki_invita_action__8bec8a_idx",
            ),
        ),
    ]
