# Generated by Django 6.0 on 2026-06-19 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0064_emailverificationticket_invitation_code_snapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="competition_contribution_score",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="wiki_contribution_score",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.CreateModel(
            name="CompetitionContributionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("target_title", models.CharField(blank=True, max_length=220)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("schedule_approved", "锦标赛通过审核"),
                            ("schedule_rollback", "锦标赛收益回滚"),
                            ("notice_approved", "赛事公告通过审核"),
                            ("notice_rollback", "赛事公告收益回滚"),
                            ("practice_link_approved", "补题链接通过审核"),
                            ("practice_link_rollback", "补题链接收益回滚"),
                            ("admin_adjustment", "管理员调整"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("delta", models.IntegerField()),
                ("balance_after", models.IntegerField()),
                ("is_rollback", models.BooleanField(db_index=True, default=False)),
                (
                    "event_key",
                    models.CharField(
                        blank=True, max_length=180, null=True, unique=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_competition_contribution_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competition_contribution_events",
                        to="wiki.competitionnotice",
                    ),
                ),
                (
                    "practice_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contribution_events",
                        to="wiki.competitionpracticelink",
                    ),
                ),
                (
                    "practice_proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contribution_events",
                        to="wiki.competitionpracticelinkproposal",
                    ),
                ),
                (
                    "schedule_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contribution_events",
                        to="wiki.competitionscheduleentry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_contribution_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="wiki_compet_user_id_e56bf2_idx",
                    ),
                    models.Index(
                        fields=["action_type", "created_at"],
                        name="wiki_compet_action__59ac8a_idx",
                    ),
                    models.Index(
                        fields=["schedule_entry", "created_at"],
                        name="wiki_compet_schedul_b5d63e_idx",
                    ),
                    models.Index(
                        fields=["notice", "created_at"],
                        name="wiki_compet_notice__d71127_idx",
                    ),
                    models.Index(
                        fields=["practice_link", "created_at"],
                        name="wiki_compet_practic_d5f431_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WikiContributionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("article_title", models.CharField(blank=True, max_length=220)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("wiki_revision_approved", "Wiki 修订通过审核"),
                            ("wiki_revision_rollback", "Wiki 修订收益回滚"),
                            ("admin_adjustment", "管理员调整"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("delta", models.IntegerField()),
                ("balance_after", models.IntegerField()),
                ("is_rollback", models.BooleanField(db_index=True, default=False)),
                (
                    "event_key",
                    models.CharField(
                        blank=True, max_length=180, null=True, unique=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_wiki_contribution_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wiki_contribution_events",
                        to="wiki.article",
                    ),
                ),
                (
                    "revision_proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contribution_events",
                        to="wiki.revisionproposal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wiki_contribution_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="wiki_wikico_user_id_8c02f0_idx",
                    ),
                    models.Index(
                        fields=["article", "created_at"],
                        name="wiki_wikico_article_44fba9_idx",
                    ),
                    models.Index(
                        fields=["action_type", "created_at"],
                        name="wiki_wikico_action__2d52dc_idx",
                    ),
                ],
            },
        ),
    ]
