# Generated by Django 6.0 on 2026-06-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0065_user_competition_contribution_score_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneRegistrationTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone_country_code",
                    models.CharField(blank=True, default="86", max_length=8),
                ),
                ("phone_masked", models.CharField(blank=True, max_length=32)),
                ("phone_last4", models.CharField(blank=True, max_length=4)),
                ("phone_encrypted", models.TextField(blank=True)),
                ("phone_digest", models.CharField(db_index=True, max_length=128)),
                ("username_snapshot", models.CharField(max_length=150)),
                ("email_snapshot", models.EmailField(blank=True, max_length=254)),
                ("school_name_snapshot", models.CharField(max_length=120)),
                (
                    "invitation_code_snapshot",
                    models.CharField(blank=True, max_length=32),
                ),
                ("password_hash_snapshot", models.CharField(max_length=128)),
                (
                    "provider",
                    models.CharField(blank=True, default="aliyun_pnvs", max_length=40),
                ),
                (
                    "provider_out_id",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("provider_biz_id", models.CharField(blank=True, max_length=120)),
                ("provider_request_id", models.CharField(blank=True, max_length=120)),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("verify_attempt_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_ip",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "consumed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone_digest", "created_at"],
                        name="wiki_phoner_phone_d_71e2fd_idx",
                    ),
                    models.Index(
                        fields=["username_snapshot", "created_at"],
                        name="wiki_phoner_usernam_954403_idx",
                    ),
                ],
            },
        ),
    ]
