# Generated by Django 6.0 on 2026-07-19 06:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0066_phoneregistrationticket"),
    ]

    operations = [
        migrations.CreateModel(
            name="PulseDailyEdition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True, unique=True)),
                ("poll_prompt", models.CharField(max_length=300)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator preset"),
                            ("hot", "Site hot topic"),
                            ("random", "Curated random"),
                        ],
                        default="random",
                        max_length=16,
                    ),
                ),
                ("source_payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        db_index=True,
                        default="published",
                        max_length=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_pulse_editions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pulse_edition",
                        to="wiki.question",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PulsePollOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("text", models.CharField(max_length=180)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll_options",
                        to="wiki.pulsedailyedition",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="PulsePollVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll_votes",
                        to="wiki.pulsedailyedition",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="wiki.pulsepolloption",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pulse_poll_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PulseRedemptionCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code_lookup_digest", models.CharField(max_length=64, unique=True)),
                ("code_hash", models.CharField(max_length=128)),
                ("code_hint", models.CharField(blank=True, max_length=16)),
                ("reward_payload", models.JSONField(default=dict)),
                (
                    "starts_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("ends_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("max_uses", models.PositiveIntegerField(default=1)),
                ("per_user_limit", models.PositiveIntegerField(default=1)),
                ("used_count", models.PositiveIntegerField(default=0)),
                ("is_enabled", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_pulse_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PulseRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=180, unique=True)),
                ("reward_payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pulse_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemptions",
                        to="wiki.pulseredemptioncode",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PulseUserDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_date", models.DateField(db_index=True)),
                ("community_completed_at", models.DateTimeField(blank=True, null=True)),
                ("community_rewarded_at", models.DateTimeField(blank=True, null=True)),
                ("poll_completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "challenge_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "Rating problem"),
                            ("B", "Virtual participation"),
                        ],
                        db_index=True,
                        max_length=1,
                    ),
                ),
                ("challenge_completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "signed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_days",
                        to="wiki.pulsedailyedition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pulse_days",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-business_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PulseChallengeAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_date", models.DateField(db_index=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[("daily", "Daily"), ("makeup", "Makeup")],
                        db_index=True,
                        default="daily",
                        max_length=16,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("A", "Rating problem"),
                            ("B", "Virtual participation"),
                        ],
                        db_index=True,
                        max_length=1,
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField(default=0)),
                ("rating_snapshot", models.PositiveSmallIntegerField(default=800)),
                ("target_key", models.CharField(db_index=True, max_length=80)),
                ("target_data", models.JSONField(default=dict)),
                (
                    "assigned_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("deadline_at", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("replaced", "Replaced"),
                        ],
                        db_index=True,
                        default="assigned",
                        max_length=16,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("completion_data", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pulse_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_day",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_assignments",
                        to="wiki.pulseuserday",
                    ),
                ),
            ],
            options={
                "ordering": ["-business_date", "-sequence", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CodeforcesBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("handle", models.CharField(db_index=True, max_length=24)),
                ("handle_ci", models.CharField(db_index=True, max_length=24)),
                (
                    "active_handle_ci",
                    models.CharField(blank=True, max_length=24, null=True, unique=True),
                ),
                ("rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(db_index=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_submission_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "unbound_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "rebind_not_before",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("unbind_reason", models.CharField(blank=True, max_length=300)),
                (
                    "active_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_codeforces_binding",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codeforces_binding_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unbound_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="codeforces_unbind_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-verified_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["handle_ci", "verified_at"],
                        name="wiki_codefo_handle__3f7c71_idx",
                    ),
                    models.Index(
                        fields=["owner", "verified_at"],
                        name="wiki_codefo_owner_i_a175f2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CodeforcesEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submission_id", models.PositiveBigIntegerField(unique=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("binding", "Binding"),
                            ("challenge", "Challenge"),
                            ("makeup", "Makeup"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                (
                    "source_id",
                    models.PositiveBigIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codeforces_evidence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "purpose", "created_at"],
                        name="wiki_codefo_user_id_a2224c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CodeforcesVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("handle", models.CharField(max_length=24)),
                ("handle_ci", models.CharField(db_index=True, max_length=24)),
                ("baseline_submission_id", models.PositiveBigIntegerField(default=0)),
                ("rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("issued_at", models.DateTimeField(db_index=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "verified_submission_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codeforces_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "status", "expires_at"],
                        name="wiki_codefo_user_id_a799f7_idx",
                    ),
                    models.Index(
                        fields=["handle_ci", "status", "expires_at"],
                        name="wiki_codefo_handle__d33772_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PulseLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset",
                    models.CharField(
                        choices=[
                            ("point", "Point"),
                            ("reroll", "Reroll ticket"),
                            ("makeup", "Makeup ticket"),
                            ("super_makeup", "Super makeup ticket"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("delta", models.IntegerField()),
                ("balance_after", models.IntegerField()),
                ("event_key", models.CharField(max_length=180, unique=True)),
                (
                    "source_type",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                (
                    "source_id",
                    models.PositiveBigIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pulse_ledger_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pulse_ledger_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "asset", "created_at"],
                        name="wiki_pulsel_user_id_dd3525_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PulseMakeup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("target_date", models.DateField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("normal", "Normal"), ("super", "Super")],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="makeup",
                        to="wiki.pulsechallengeassignment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pulse_makeups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-target_date", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "target_date"), name="pulse_unique_makeup_date"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="pulsepolloption",
            constraint=models.UniqueConstraint(
                fields=("edition", "position"), name="pulse_unique_poll_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="pulsepollvote",
            constraint=models.UniqueConstraint(
                fields=("edition", "user"), name="pulse_unique_user_vote"
            ),
        ),
        migrations.AddIndex(
            model_name="pulseredemption",
            index=models.Index(
                fields=["code", "user", "created_at"],
                name="wiki_pulser_code_id_34b97a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pulseuserday",
            index=models.Index(
                fields=["user", "signed_at", "business_date"],
                name="wiki_pulseu_user_id_3ee216_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pulseuserday",
            index=models.Index(
                fields=["business_date", "challenge_mode"],
                name="wiki_pulseu_busines_fc558e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="pulseuserday",
            constraint=models.UniqueConstraint(
                fields=("user", "business_date"), name="pulse_unique_user_day"
            ),
        ),
        migrations.AddIndex(
            model_name="pulsechallengeassignment",
            index=models.Index(
                fields=["user", "business_date", "status"],
                name="wiki_pulsec_user_id_ee0c07_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pulsechallengeassignment",
            index=models.Index(
                fields=["deadline_at", "status"], name="wiki_pulsec_deadlin_e54de5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pulsechallengeassignment",
            constraint=models.UniqueConstraint(
                fields=("user", "purpose", "business_date", "sequence"),
                name="pulse_unique_assignment_sequence",
            ),
        ),
    ]
