# Generated by Django 6.0 on 2026-07-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0068_pulse_reward_campaign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityauditlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login_success", "Login Success"),
                    ("login_failed", "Login Failed"),
                    ("login_locked", "Login Locked"),
                    ("login_denied", "Login Denied"),
                    ("register_success", "Register Success"),
                    ("register_code_sent", "Register Code Sent"),
                    ("logout", "Logout"),
                    ("password_change_requested", "Password Change Requested"),
                    ("password_changed", "Password Changed"),
                    ("password_reset_requested", "Password Reset Requested"),
                    ("password_reset_completed", "Password Reset Completed"),
                    ("email_change_requested", "Email Change Requested"),
                    ("email_changed", "Email Changed"),
                    ("user_banned", "User Banned"),
                    ("user_unbanned", "User Unbanned"),
                    ("user_soft_deleted", "User Soft Deleted"),
                    ("user_hard_deleted", "User Hard Deleted"),
                    ("user_reactivated", "User Reactivated"),
                    ("user_role_changed", "User Role Changed"),
                    ("codeforces_bound", "Codeforces Bound"),
                    ("codeforces_unbound", "Codeforces Unbound"),
                    ("pulse_asset_granted", "Pulse Asset Granted"),
                    ("pulse_campaign_created", "Pulse Campaign Created"),
                    ("pulse_campaign_updated", "Pulse Campaign Updated"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
